### ISSUE TITLE
Source message author username/ID

### ISSUE THREAD

**Issue by Shmalle** [Mssjim/discord-server-mirror#1]
Hey there! _(This is more or less an enhancement than issue)._

I would really like to see an option that enables us to see **who** wrote the mirrored message. Lets say there is a message from "Alex" with the ID "2134567890" in the reader channel, then the write channel should receive something like "Message from Alex (2134567890): message content".

**Comment by Mssjim** [comment]
Now you can do that with 'showAuthor' flag as true in the settings 🙏

**Comment by Shmalle** [comment]
ON GOD I LOVE YOU!!
![image](https://user-images.githubusercontent.com/72462771/184115648-9a7df2b9-5bac-4c7c-a881-96b49cebe729.png)
Satisfied af.
