### ISSUE TITLE
Multiples

### ISSUE THREAD

**Issue by Jake22262** [Mssjim/discord-server-mirror#12]
How can I do multiple read and write channels?

**Comment by Mssjim** [comment]
You need to pass an array of channels in ‘settings.json`
like this: 
```json
...
    "readChannel": ["read channel1", "read channel2", "read channel3"],
    "writeChannel": ["write channel1", "write channel2", "write channel3"],
...
```

**Comment by Jake22262** [comment]
I just tried 2 times, didnt work.

**Comment by Mssjim** [comment]
Are you sure that you made a recent clone and that your `settings.json` is set correctly?

An example using the default settings, passing 4 channels respectively: 

![Sem título](https://user-images.githubusercontent.com/43995964/207705679-cb58fe22-dea3-4178-952f-3ab7b1fe03fc.png)

```json
{
    "readChannel": ["1052675188724088901", "1052675220340748202"],
    "writeChannel": ["1052675268923367403", "1052675298375766104"],
    "twoSided": true,
    "sendAttachments": true,
    "convertEmojis": true,
    "showAuthor": false,
    "showAvatar": false,
    "typing": true,
    "ignoreWebhooks": false,
    "ignoreMentions": false,
    "prefix": "",
    "tokens": [
        "Nz3X4MPL3T0K3NU0N3X4MPL3T0K3N3X4MPL3.T0K3N.3X4MPL3T0K3N3X4MPL3T0K3N3X4MPL3T0K3N"
    ],
    "nicknames": {
        "": ""
    },
    "blacklist": [
        ""
    ]
}
```

By sending a message containing the channel number on each of them, the result will be:
![image](https://user-images.githubusercontent.com/43995964/207706080-c1e34ea3-34ec-457c-a7c2-8b05d3b6150e.png)
