### ISSUE TITLE
Nicknames for User IDs

### ISSUE THREAD

**Issue by Shmalle** [Mssjim/discord-server-mirror#6]
Hey, this is definitely an enhancement rather than a required feature.
So what I was thinking of was, that one can **set a nickname with an ID**, which means that instead of "Username#1234 (123456789)" it shows the nickname I set. 
So if I say "ID=123456789, Nickname=RandomGuy", the messages in the writeChannel will appear as "RandomGuy (1)", where (1) is the number of _which_ entry in the list of nicknames the user is, simply to recheck if there's any problem/typo/mistake or duplicated entry.

**Comment by Mssjim** [comment]
Done 🙏 

```json
"nicknames": {
    "123456789": "RandomGuy"
}
```
