### ISSUE TITLE
Command to SEND a message

### ISSUE THREAD

**Issue by Shmalle** [Mssjim/discord-server-mirror#7]
Reading through the messages makes me think "oy, its time to intervene" but I am a too lazy peace of XXXXXX to login into the account for one single message.
I would absolutely appreciate a feature whereas one can set a prefix (such as !send) to send a message through a token that is set to send messages.

So the config would be like:
"Tokens: TokenFor1.Acc"
"Token-sendmessage: TokenFor2.Acc"

Thanks for readin 🤙

**Comment by Mssjim** [comment]
So, if you enable 'twoSided', the messages will be mirrored in both ways, so when you send any message in 'writeChannel' it will be sent to 'readChannel'.

Or would you like the account that sends the message to "readChannel" to be different from the account that clones the messages?

**Comment by Mssjim** [comment]
Something like

```json
"readTokens": [],
"writeTokens: []
```
will solve or do you need something more specific, so that the mirror continues with several accounts and you use another alternative to send messages through commands?

**Comment by Shmalle** [comment]
First of all, thanks for taking your time!
I want the accounts to clone and to write to be different.
I always have twoSided off.
One account keeps reading the readChannel and sends to the writeChannel.
One accounts reads the writeChannel and sends to the readChannel __**but only**__ if a set prefix was used.
Below is a graphic to explain what I try to explain.

![MirroringIssue](https://user-images.githubusercontent.com/72462771/190861627-7d847264-f38a-4f01-938c-9e4fcb0bb1e2.png)

**Comment by Mssjim** [comment]
Sorry for the delay, I was kind of busy xD
I understand what you want 🙏
Now you can set a custom prefix in `settings.json`, the last token in the array will be used for sending messages.

Your `settings.json` will be look like:
```json
    "prefix": "!send",
    "tokens": [
        "TokenFor1.Acc",
        "TokenFor2.Acc"
    ],
```

If you want to add more accounts in the future, just keep the account token to send messages as last

It is worth mentioning that:
- All your `read Channel` messages will be ignored, even if they were not sent via commands
- When defining a prefix, the `twoSided` will be ignored

**Comment by Shmalle** [comment]
Thats awesome, thank you very much! In case I have any questions, which I might have, I will come back to here.
