### ISSUE TITLE
hi usernames not working

### ISSUE THREAD

**Issue by davidpr1** [Mssjim/discord-server-mirror#9]
it wont change the user name.. it just stay what ever the tokens have    and amazing job here

 "nicknames": {
        "userid": "jose"
    }

**Comment by davidpr1** [comment]
theres a way to copy webhook messages to?

**Comment by Mssjim** [comment]
Hi, the `nicknames` flag is just for show a custom name when `showAuthor` is true, like this:
![image](https://user-images.githubusercontent.com/43995964/189710499-d2617e42-70fb-41da-9411-b3ba2538a395.png)

It was a solution for [this issue](https://github.com/Mssjim/discord-server-mirror/issues/6#issue-1354129825)
In the future i will implement a webhook system too, to display author details 🙏 



> theres a way to copy webhook messages to?
The webhooks messages were being ignored but now they are being copied too 👍

**Comment by DOFER998** [comment]
> Hi, the `nicknames` flag is just for show a custom name when `showAuthor` is true, like this: ![image](https://user-images.githubusercontent.com/43995964/189710499-d2617e42-70fb-41da-9411-b3ba2538a395.png)
> 
> It was a solution for [this issue](https://github.com/Mssjim/discord-server-mirror/issues/6#issue-1354129825) In the future i will implement a webhook system too, to display author details pray
> 
> > theres a way to copy webhook messages to?
> 
> The webhooks messages were being ignored but now they are being copied too +1

With the detection of pending transfers using  **webhooks**
